import { StyleSheet } from "react-native";
import { UI } from "./ui";

export const sharedStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: UI.colors.canvas },
  screenContent: {
    width: "100%",
    maxWidth: UI.layout.contentMaxWidth,
    alignSelf: "center",
    padding: UI.layout.screenPadding,
    paddingTop: UI.spacing.xl,
    paddingBottom: UI.layout.bottomPadding,
  },
  formContent: {
    width: "100%",
    maxWidth: UI.layout.formMaxWidth,
    alignSelf: "center",
    padding: UI.layout.screenPadding,
    paddingBottom: UI.layout.bottomPadding,
  },
  pageTitle: {
    color: UI.colors.ink,
    fontSize: UI.type.pageTitle,
    lineHeight: 36,
    fontWeight: "800",
    letterSpacing: -0.7,
  },
  pageSubtitle: {
    color: UI.colors.inkMuted,
    fontSize: UI.type.body,
    lineHeight: 20,
    marginTop: UI.spacing.xxs,
    marginBottom: UI.spacing.lg,
  },
  card: {
    backgroundColor: UI.colors.surface,
    borderRadius: UI.radius.large,
    padding: UI.spacing.lg,
    borderWidth: 1,
    borderColor: UI.colors.border,
    ...UI.shadowSubtle,
  },
  sectionTitle: {
    color: UI.colors.ink,
    fontSize: UI.type.sectionTitle,
    lineHeight: 24,
    fontWeight: "800",
    marginBottom: UI.spacing.sm,
  },
  label: {
    color: UI.colors.ink,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    marginBottom: UI.spacing.xs,
    marginTop: UI.spacing.md,
  },
  input: {
    minHeight: UI.control.inputHeight,
    color: UI.colors.ink,
    backgroundColor: UI.colors.surface,
    borderWidth: 1,
    borderColor: UI.colors.borderStrong,
    borderRadius: UI.radius.small,
    paddingHorizontal: UI.spacing.sm,
    paddingVertical: UI.spacing.sm,
    fontSize: UI.type.body,
  },
  inputWeb: {
    outlineColor: UI.colors.focus,
    outlineOffset: 2,
  } as any,
  chip: {
    minHeight: UI.control.minTouchTarget,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: UI.colors.borderStrong,
    borderRadius: UI.radius.pill,
    paddingVertical: UI.spacing.xs,
    paddingHorizontal: UI.spacing.sm,
    backgroundColor: UI.colors.surface,
  },
  chipSelected: {
    backgroundColor: UI.colors.ink,
    borderColor: UI.colors.ink,
  },
  chipText: {
    color: UI.colors.inkMuted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  chipTextSelected: { color: UI.colors.onDark },
});
