export const UI = {
  colors: {
    canvas: "#F4F6FA",
    surface: "#FFFFFF",
    surfaceMuted: "#F8FAFC",
    ink: "#101828",
    inkMuted: "#667085",
    inkSubtle: "#98A2B3",
    border: "#E4E7EC",
    borderStrong: "#D0D5DD",
    focus: "#E92C55",
    focusRing: "#FBC5CF",
    primary: "#E92C55",
    primaryPressed: "#C91F45",
    primarySoft: "#FFF0F3",
    success: "#067647",
    successSoft: "#ECFDF3",
    warning: "#B54708",
    warningSoft: "#FFFAEB",
    danger: "#B42318",
    dangerSoft: "#FEF3F2",
    onDark: "#FFFFFF",
    onDarkMuted: "#D0D5DD",
    onDarkSubtle: "#98A2B3",
    positiveOnDark: "#6CE9A6",
    negativeOnDark: "#FDA29B",
    disabled: "#F2F4F7",
    disabledText: "#98A2B3",
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
    xxxl: 48,
  },
  radius: {
    xsmall: 8,
    small: 10,
    medium: 14,
    large: 20,
    pill: 999,
  },
  type: {
    caption: 11,
    small: 12,
    body: 14,
    bodyLarge: 15,
    sectionTitle: 18,
    metric: 24,
    pageTitle: 30,
  },
  control: {
    minTouchTarget: 44,
    inputHeight: 48,
    buttonHeight: 44,
  },
  layout: {
    screenPadding: 20,
    screenPaddingNarrow: 16,
    contentMaxWidth: 800,
    formMaxWidth: 680,
    bottomPadding: 48,
  },
  shadow: {
    shadowColor: "#101828",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  shadowSubtle: {
    shadowColor: "#101828",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
} as const;
